### ISSUE TITLE
There is no subscription available.

### ISSUE THREAD

**Issue by Pamposgsk** [LimeDeck/nova-cashier-overview#12]
Hi,
iam using latest laravel& laravel nova  frameworks.I've installed laravel cashier and migrations.I install nova cashier overview.I fill the database required fields based on stripe dashboard but the result
in users detail view isthe following :There is no subscription available.
Is there any issue with the tool or iam missing something.
Could you please share some more info on how to make it work?
thanks in advanced

**Comment by scramatte** [comment]
Hi,

I've got the same issue, how have you solve the problem?
