### ISSUE TITLE
Laravel Cashier 13.x

### ISSUE THREAD

**Issue by jazzzym** [LimeDeck/nova-cashier-overview#26]
Hi!

After upgrading to laravel-cashier 13.x limedeck/nova-cashier-overview is stopped to work.

Do you have any plans to update  limedeck/nova-cashier-overview to work with the latest laravel/cashier codebase?

Thanks in advance
Marton JazzzyM Voros

PS: This is a great tool for laravel nova. Thanks for your work

**Comment by midesweb** [comment]
I have solved this issue doing this steps:

- Publishing nova config (php artisan vendor:pusblish)
- Creating a configuration variable called "model"

```
'model' => env('CASHIER_MODEL', "App\User"),
```
