### ISSUE TITLE
Install problem: requirements could not be resolved

### ISSUE THREAD

**Issue by core45** [LimeDeck/nova-cashier-overview#3]
I have installed:

```
Laravel 6.9.0
Nova 2.7
Spark 9.1.1
```

I do

`
composer require limedeck/nova-cashier-overview
`

and it gives me an error as follows:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for limedeck/nova-cashier-overview ^1.0 -> satisfiable by limedeck/nova-cashier-overview[1.0.0].
    - limedeck/nova-cashier-overview 1.0.0 requires laravel/nova ^2.0 -> no matching package found.
```

**Comment by rudowastaken** [comment]
Hello @core45 , I've just tried it on a fresh Laravel install with the following required packages and versions:

```
"require": {
  "php": "^7.2",
  "fideloper/proxy": "^4.0",
  "laravel/framework": "^6.2",
  "laravel/nova": "~2.0",
  "laravel/tinker": "^2.0",
  "limedeck/nova-cashier-overview": "^1.0"
},
```

This worked just fine. I can't verify if and how Spark might affect the versions pulled by composer since we don't use it. You might want to check your composer.lock to see if you're actually using 2.x version of Nova.

**Comment by core45** [comment]
Hi again,
I have successfully installed the package but I had to do it manually by cloning the repo and changing requirements in composer.json from "^2.0" to "*"

For a reason my Nova install is 9999999-dev - it's really 2.9.2 downloaded from Nova page and installed as they say in the documentation.

**Comment by rudowastaken** [comment]
I see. Generally, I would recommend you to avoid "*" in version specifications. 

Also, it's more convenient to use Composer for installing Nova where you can specify the desired version directly: https://nova.laravel.com/docs/2.0/installation.html#installing-nova-via-composer 

Closing this issue as this is technically tied to the setup of your project.
